export const deliveryEntries =[
  {
    username: 'john_doe',
    mobile: 1234567890,
    password: 'securePass123',
    checked_in: true,
    zip_code: '12345',
    user_role: 1,
    address: '123 Main St',
    account_type: 2,
  },
  {
    username: 'jane_smith',
    mobile: 9876543210,
    password: 'strongPassword',
    checked_in: false,
    zip_code: '54321',
    user_role: 2,
    address: '456 Elm St',
    account_type: 1,
  },
  {
    username: 'bob_jones',
    mobile: 5556667777,
    password: 'secret123',
    checked_in: true,
    zip_code: '67890',
    user_role: 1,
    address: '789 Oak Ave',
    account_type: 2,
  },
  {
    username: 'alice_wonderland',
    mobile: 1112223333,
    password: 'wonderPass',
    checked_in: false,
    zip_code: '98765',
    user_role: 2,
    address: '101 Pine Rd',
    account_type: 1,
  },
  {
    username: 'charlie_chaplin',
    mobile: 9998887777,
    password: 'comedyPass',
    checked_in: true,
    zip_code: '11111',
    user_role: 1,
    address: '222 Broadway',
    account_type: 2,
  },
];

export const ordersArray = [
    {
      pickupPoint_address: "123 Main St",
      pickupPoint_phone: "555-1234",
      deliveryPoint_address: "456 Oak St",
      deliveryPoint_phone: "555-5678",
      package_type: "Small",
      parcel_value: 50,
      userId: "user123",
      pickupCoordinatesX: 1.23,
      pickupCoordinatesY: 4.56,
      deliveryCoordinatesX: 7.89,
      deliveryCoordinatesY: 10.11,
      typeOfVehicle: "Car",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      pickupPoint_address: "789 Elm St",
      pickupPoint_phone: "555-4321",
      deliveryPoint_address: "012 Pine St",
      deliveryPoint_phone: "555-8765",
      package_type: "Medium",
      parcel_value: 75,
      userId: "user456",
      pickupCoordinatesX: 2.34,
      pickupCoordinatesY: 5.67,
      deliveryCoordinatesX: 8.90,
      deliveryCoordinatesY: 12.34,
      typeOfVehicle: "Bike",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      pickupPoint_address: "345 Cedar St",
      pickupPoint_phone: "555-9876",
      deliveryPoint_address: "678 Birch St",
      deliveryPoint_phone: "555-5432",
      package_type: "Large",
      parcel_value: 100,
      userId: "user789",
      pickupCoordinatesX: 3.45,
      pickupCoordinatesY: 6.78,
      deliveryCoordinatesX: 9.01,
      deliveryCoordinatesY: 14.56,
      typeOfVehicle: "Truck",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      pickupPoint_address: "901 Maple St",
      pickupPoint_phone: "555-2109",
      deliveryPoint_address: "234 Walnut St",
      deliveryPoint_phone: "555-6543",
      package_type: "Small",
      parcel_value: 55,
      userId: "user012",
      pickupCoordinatesX: 4.56,
      pickupCoordinatesY: 7.89,
      deliveryCoordinatesX: 10.12,
      deliveryCoordinatesY: 16.78,
      typeOfVehicle: "Scooter",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Repeat similar entries for 2 more
    // ...
  ];
  